
#ifndef _C420SCD_SERVO_LIMITS_H
#define _C420SCD_SERVO_LIMITS_H


#define SERVO_FLH_MIN 65
#define SERVO_FLH_MAX 600
#define SERVO_FLH_ADDR 0
#define SERVO_FRH_MIN 50
#define SERVO_FRH_MAX 450
#define SERVO_FRH_ADDR 1
#define SERVO_BRH_MIN 50
#define SERVO_BRH_MAX 600
#define SERVO_BRH_ADDR 2
#define SERVO_BLH_MIN 200
#define SERVO_BLH_MAX 600
#define SERVO_BLH_ADDR 3

#define SERVO_FLT_MIN 100
#define SERVO_FLT_MAX 650
#define SERVO_FLT_ADDR 4
#define SERVO_FRT_MIN 100
#define SERVO_FRT_MAX 650
#define SERVO_FRT_ADDR 5
#define SERVO_BRT_MIN 100
#define SERVO_BRT_MAX 650
#define SERVO_BRT_ADDR 6
#define SERVO_BLT_MIN 75
#define SERVO_BLT_MAX 600
#define SERVO_BLT_ADDR 7

#define SERVO_FLF_MIN 100
#define SERVO_FLF_MAX 650
#define SERVO_FLF_ADDR 8
#define SERVO_FRF_MIN 100
#define SERVO_FRF_MAX 650
#define SERVO_FRF_ADDR 9
#define SERVO_BRF_MIN 100
#define SERVO_BRF_MAX 650
#define SERVO_BRF_ADDR 10
#define SERVO_BLF_MIN 100
#define SERVO_BLF_MAX 650
#define SERVO_BLF_ADDR 11

#endif _C420SCD_SERVO_LIMITS_H